version: "3.7"
services:


  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-2
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888
      
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
 
  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
 
 
  gateway:
    image: merchantpaymentgateway:latest
    expose:
      - 5050
    ports:
      - 5050:5050
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "5050"
      SERVER_GOROUTINEPOOLSIZE: "100"
      KAFKA_BROKERS: "192.168.99.1:9092"
      KAFKA_TOPIC:   "MerchantPaymentTopic"
      KAFKA_RETRY:   "2"
  
  routingEngine:
    image: merchantpaymentroutingengine:latest
    expose:
      - 7070
    ports:
      - 7070:7070
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "7070"
      KAFKA_BROKERS: "192.168.99.1:9092"
      KAFKASUB_TOPIC:   "MerchantPaymentTopic"
      KAFKASUB_GROUP:   "PaymentMerchantGrp"  
      KAFKAPUB_RETRY:   "2"
      ROUTINGRULE_TYPE: "DROOL"
  
  
  