version: "3.2"

networks:
  default:
    external:
      name: my_net
services:

  server:
    image: intelligentpaymentrouting/merchantpayment-gateway:latest
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "9090"
      SERVER_GOROUTINEPOOLSIZE: "2"
      KAFKA_BROKERS: "192.168.56.1:9092"
      KAFKA_TOPIC:   "MerchantPaymentTopic"
      KAFKA_RETRY:   "2"



